### ISSUE TITLE
repo name / plugin name

### ISSUE THREAD

**Issue by SethTisue** [scala/sbt-scala-module#23]
it bugs me that the repo is named `sbt-scala-modules` but the plugin is published as `scala-module-plugin`. as a result I have trouble remembering both names

I suggest we:

* change the repo name to `sbt-scala-module`, singular
* publish the plugin as `sbt-scala-module` as well (as per http://www.scala-sbt.org/0.13/docs/Plugins-Best-Practices.html)

objections?

**Comment by lrytz** [comment]
I totally agree!

**Comment by dwijnand** [comment]
I don't mean to feature creep this ticket (but I also don't feel strongly enough to create a new one), but with regards to the plugin best practices there's also the one about key namespace clashes: http://www.scala-sbt.org/0.13/docs/Plugins-Best-Practices.html#Avoid+namespace+clashes.

**Comment by SethTisue** [comment]
I have renamed the repository. keeping the issue open until I actually publish 1.0.9, which I'll do shortly

**Comment by SethTisue** [comment]
I now thiiiiiiink I did everything right, but the final step, where I added my repo to https://bintray.com/sbt/sbt-plugin-releases, has to be approved by @eed3si9n, apparently

**Comment by dwijnand** [comment]
It's good now: https://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-lang.modules/sbt-scala-module/scala_2.10/sbt_0.13/1.0.9/.
