### ISSUE TITLE
keys should do the right autoPlugin dance

### ISSUE THREAD

**Issue by SethTisue** [scala/sbt-scala-module#30]
so that e.g. this doesn't happen:

```
> show mimaPreviousVersion
[info] Some(1.0.6)
> set mimaPreviousVersion := None
<set>:1: error: not found: value mimaPreviousVersion
mimaPreviousVersion := None
```

(note `set ScalaModulePlugin.mimaPreviousVersion := None` works)

and that this isn't needed:

```
import ScalaModulePlugin._
```

@dwijnand describes the dance as "autoImport (or aliases, or mixed-in, or whatever)"

**Comment by dwijnand** [comment]
Reference http://www.scala-sbt.org/0.13/docs/Plugins.html#Controlling+the+import+with+autoImport

**Comment by Philippus** [comment]
If the goal is to not need the import, we would also need to move some `val`s (like `disablePublishing`) inside the `autoImport` object.
