### ISSUE TITLE
support sbt 1.x

### ISSUE THREAD

**Issue by SethTisue** [scala/sbt-scala-module#32]
practice what we preach

**Comment by godenji** [comment]
Can't `publishLocal` scala-xml with sbt 1.0 support due to this issue.

**Comment by SethTisue** [comment]
on hold until there is an sbt 1.x release that is Scala 2.13 friendly (the ticket on that is https://github.com/sbt/sbt/issues/3427)

**Comment by SethTisue** [comment]
1.1.0 is 2.13-friendly, so this can move forward now.

**Comment by lrytz** [comment]
cool! i'm still planning to push my work on supporting js/native through, which will (most likely) include an sbt 1 upgrade. current state summarized in https://github.com/scala/scala-parser-combinators/pull/132#issuecomment-342553814.

**Comment by Sciss** [comment]
ping!

**Comment by SethTisue** [comment]
using sbt 1 requires building on Java 8. this is problematic because we still build the modules for Scala 2.11 on Java 6.

I suggest we drop Scala 2.11 support in all the modules, or at least, in any module wanting to upgrade to sbt 1 on its current development branch. (modules wanting to continue to release new versions for Scala 2.11 could do so from an older branch using sbt 0.13.)

then we can standardize on Java 8 and everything becomes simpler.

what do you think @lrytz?

**Comment by Sciss** [comment]
I wouldn't drop 2.11 support. Is there a problem compiling modules for 2.11 running on a JDK 8? you can still have a java target of 1.6 if it includes Java sources.

**Comment by SethTisue** [comment]
> Is there a problem compiling modules for 2.11 running on a JDK 8?

only sort of. the danger is that you accidentally use Java 7 or 8 APIs, and then the resulting module doesn't work on Java 6 or 7.

so, another possibility in this space is to keep 2.11 support but drop Java 6 and 7 support.

**Comment by Sciss** [comment]
Right - so I will opt for sticking to sbt 0.13 for the Swing module then.

**Comment by dwijnand** [comment]
> another possibility in this space is to keep 2.11 support but drop Java 6 and 7 support and build everything on 8.

You could do that in a new version series of this plugin, so modules could independently give up on Java 6/7 and upgrade to sbt 1.

**Comment by SethTisue** [comment]
> You could do that in a new version series of this plugin 

Yeah. I like it. We could start with scala-parallel-collections, which is already Scala 2.12+/Java8+ only anyway.

I've also submitted a PR to scala-async to drop 2.11 support there, not sure if Jason will merge that one or not.

**Comment by SethTisue** [comment]
(Lukas is on vacation this week, so we'll have to wait for this thoughts.)

**Comment by SethTisue** [comment]
> Right - so I will opt for sticking to sbt 0.13 for the Swing module then.

I've made a new ticket to discuss that separately: https://github.com/scala/scala-swing/issues/79

**Comment by som-snytt** [comment]
I tried this today, in fact on the swing module.

**Comment by SethTisue** [comment]
I deleted the master branch and created 1.x and 2.x branches (pointing to the same commit, to start). 1.x can continue as before, and I'll working on switching to sbt 1 on the 2.x branch

**Comment by SethTisue** [comment]
WIP at #50. (I am secretly hoping to nerd-snipe @dwijnand into helping with the needed  code changes — shhhhhhhhhh!)

**Comment by SethTisue** [comment]
keeping the ticket open until we've actually published a release and used it on at least one actual module

**Comment by SethTisue** [comment]
plugin 2.0.0 is published

I'm trying it out at https://github.com/scala/scala-partest/pull/116 and https://github.com/scala/scala-partest/releases/tag/v1.1.9 and https://github.com/scala/scala/pull/7774

**Comment by SethTisue** [comment]
well I'm running some partests in scala/scala locally and they're passing, so I think we can declare victory here
