### ISSUE TITLE
sbt-osgi support that works on both Java 6 and Java 9?

### ISSUE THREAD

**Issue by SethTisue** [scala/sbt-scala-module#35]
currently we have:

```
// Version 0.9.1 requires Java 8 (on 6 we get NoClassDefFoundError: java/util/function/Predicate).
// We still run our plugin builds for 2.11 on Java 6, so we cannot upgrade.
addSbtPlugin("com.typesafe.sbt" % "sbt-osgi" % "0.8.0")
```

but 0.8.0 doesn't work on Java 9 and doesn't support sbt 1.0 either, so being stuck on this version is a problem for multiple reasons

@lrytz what do you think, how should we proceed here?

**Comment by retronym** [comment]
Can we predicate the choice of OSGi plugin on the ambient JVM version?

**Comment by dwijnand** [comment]
We'd have to back-publish an 0.8.x release for sbt 1 to not also be sbt 0.13 only.

**Comment by SethTisue** [comment]
> Can we predicate the choice of OSGi plugin on the ambient JVM version?

trying it at https://github.com/scala/scala-xml/pull/220

**Comment by SethTisue** [comment]
for the modules/branches that continue to build on Java 6, the scala/scala-xml#220 workaround seem fine. I just applied it to scala-parser-combinators as well.

so we should just include that workaround in the next version of this plugin.

**Comment by SethTisue** [comment]
#50 upgrades the new 2.x branch (for sbt 1) to latest sbt-osgi

the 1.x branch (for sbt 0.13) can just stick with what it is
