### ISSUE TITLE
Add Automatic-Module-Name to MANIFEST.INF to all modules

### ISSUE THREAD

**Issue by schrepfler** [scala/sbt-scala-module#71]
In order to increase compatibility on JDK versions with modules consider adding Automatic-Module-Name in the MANIFEST.INF along the lines of akka/akka#23960 or perhaps even implement properly the module-info descriptor.
I've raised https://github.com/scala/scala-xml/issues/367 https://github.com/scala/scala-collection-compat/issues/263 https://github.com/scala/scala-java8-compat/issues/168 https://github.com/scala/scala-collection-contrib/issues/65 https://github.com/scala/scala-parallel-collections/issues/82 and https://github.com/scala/scala-parser-combinators/issues/248 as I wasn't aware of this project.

**Comment by lrytz** [comment]
Here's how this was added to scala/scala: https://github.com/scala/scala/pull/6395. I think the same should apply to modules.

**Comment by schrepfler** [comment]
Just a note, this will not be enough to address building with jlink (it seems) as it seems automodules aren’t supported/strict enough.

**Comment by SethTisue** [comment]
PR: #128, inspired by @makingthematrix's additional pressure at https://users.scala-lang.org/t/scala-jdk-11-and-jpms/6102/37
